baseURL = "https://syarif-software-engineer.pages.dev/"
languageCode = "id"
title = "Syarif Software Engineer"
theme = "PaperMod"

[params]
  homeInfoParams = {Title = "SSE", Content = "Hal-hal kecil yang saya pelajari setiap hari terkait software engineering."}
  ShowReadingTime = true
  ShowTags = true

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 20
